klife/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from web import urls as webapp_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', include(webapp_urls, namespace='products')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.contrib import admin
from django.urls import path
from .views import (product_list,
                    product_create,
                    product_detail,
                    product_category,
                    product_update,
                    index_view,
                    contacts,
                    image_upload,
                    checkout,
                    gallery)

app_name = 'webapp'
urlpatterns = [
    path('admin/', admin.site.urls),

    path(r'', index_view, name='home'),

    path(r'add/', product_create, name='add'),
    path(r'products/', product_list, name='products'),
    path(r'products/checkout.html', checkout, name='checkout'),
    # path(r'(?P<cat>)/$', product_category, name='category'),
    path(r'products/?P<cat>/', product_category, name='category'),
    path(r'products/<int:pk>/', product_detail, name='detail'),
    path(r'products/<int:pk>/edit/', product_update, name='edit'),

    path(r'contacts/', contacts, name='contacts'),

    path(r'gallery/', gallery, name='gallery'),
    path(r'upload/', image_upload, name='upload'),
]

templates/includes/navbar.html
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">KENYAN LIFESTYLE</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navbar">
            <ul class="nav navbar-nav navbar-right">
                <li class="active"><a href="/">HOME <span class="sr-only">(current)</span></a></li>
                <li><a href="{% url 'products:contacts' %}">CONTACTS</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                     aria-expanded="false">PRODUCTS <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'products:add' %}">Add Product</a></li>
{#                        <li><a href="#">Action</a></li>#}
{#                        <li><a href="#">Another action</a></li>#}
{#                        <li><a href="#">Something else here</a></li>#}
{#                        <li role="separator" class="divider"></li>#}
{#                        <li><a href="#">Separated link</a></li>#}
{#                        <li role="separator" class="divider"></li>#}
{#                        <li><a href="#">One more separated link</a></li>#}
                    </ul>
                </li>
                <li><a href="{% url 'products:gallery' %}">GALLERY</a></li>
                <li class="shoecart shoecart2 cart cart box_1">
                    <form action="#" method="post" class="last">
                        <input type="hidden" name="cmd" value="_cart">
                        <input type="hidden" name="display" value="1">
                        <button class="top_shoe_cart" type="submit" name="submit" value=""><i class="fa fa-cart-arrow-down" aria-hidden="true"></i></button>
                    </form>
                </li>
{#                <li><a href="admin/">ADMIN</a></li>#}
{#                <form class="navbar-form navbar-right">#}
{#                    <div class="form-group">#}
{#                        <input type="text" name="q" class="form-control" value="{{ request.GET.q }}"#}
{#                               placeholder="Search"/>#}
{#                    </div>#}
{#                    <button type="submit" class="btn btn-default">Submit</button>#}
{#                </form>#}
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
{##}
{#<div class="top_nav_right">#}
{#					<div class="shoecart shoecart2 cart cart box_1">#}
{#						<form action="#" method="post" class="last">#}
{#							<input type="hidden" name="cmd" value="_cart">#}
{#							<input type="hidden" name="display" value="1">#}
{#							<button class="top_shoe_cart" type="submit" name="submit" value=""><i class="fa fa-cart-arrow-down" aria-hidden="true"></i></button>#}
{#						</form>#}
{#					</div>#}
{#				</div>#}