klife/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from web import urls as webapp_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', include(webapp_urls, namespace='products')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.contrib import admin
from django.urls import path
from .views import (product_list,
                    product_create,
                    product_detail,
                    product_category,
                    product_update,
                    index_view,
                    contacts,
                    image_upload,
                    checkout,
                    gallery)

app_name = 'webapp'
urlpatterns = [
    path('admin/', admin.site.urls),

    path(r'', index_view, name='home'),

    path(r'add/', product_create, name='add'),
    path(r'products/', product_list, name='products'),
    path(r'products/checkout.html', checkout, name='checkout'),
    # path(r'(?P<cat>)/$', product_category, name='category'),
    path(r'products/?P<cat>/', product_category, name='category'),
    path(r'products/<int:pk>/', product_detail, name='detail'),
    path(r'products/<int:pk>/edit/', product_update, name='edit'),

    path(r'contacts/', contacts, name='contacts'),

    path(r'gallery/', gallery, name='gallery'),
    path(r'upload/', image_upload, name='upload'),
]

templates/base_layout.html
{% load static %}
<!DOCTYPE HTML>
<html lang="en">
<head profile="http://www.w3.org/2005/10/profile">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="icon" 
      type="image/png" 
      href="{% static 'web/images/favicon.png' %}">
    <title>KENYAN LIFESTYLE|{{ title }}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content="" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); },
        false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- Custom Theme files -->
    <link href="{% static 'web/css/bootstrap.css' %}" rel="stylesheet">
{#    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">#}
{#    <link rel="stylesheet" href="{% static 'web/css/netflixCarousel.css' %}">#}
    <link rel="stylesheet" href="{% static 'web/css/flexslider.css' %}">
    <link rel="stylesheet" href="{% static 'web/css/easy-responsive-tabs.css' %}">
    <link rel="stylesheet" href="{% static 'web/css/jquery-ui1.css' %}">
    <link rel="stylesheet" href="{% static 'web/css/shop.css' %}">
    <link rel="stylesheet" href="{% static 'web/css/checkout.css' %}">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">


    {% block stylesheet %}{% endblock stylesheet %}

    <link href="{% static 'web/css/style.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- //Custom Theme files -->
    <!-- js -->
    <!-- //js -->
    <!-- web-fonts -->
    <link href="//fonts.googleapis.com/css?family=Roboto+Condensed:300,300i,400,400i,700" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Playfair+Display:400,400i,700,700i,900,900i" rel="stylesheet">
    <!-- //web-fonts -->
{#    <style>#}
{#        .preload{#}
{#            width: 100%;#}
{#            min-height: 100%;#}
{#            z-index: 1000;#}
{#            background-color: #333;#}
{#            position: fixed;#}
{#        }#}
{#        .spinner{#}
{#            position: absolute;#}
{#            top: 0;#}
{#            bottom: 0;#}
{#            left: 0;#}
{#            right: 0;#}
{#            margin: auto;#}
{#            border: transparent 5px solid;#}
{#            border-radius: 100%;#}
{#        }#}
{#        #spinner1{#}
{#            width: 100px;#}
{#            height: 100px;#}
{#            border-top-color: azure;#}
{#            border-bottom-color: azure;#}
{#            animation: spin 1.8s infinite linear;#}
{#        }#}
{#        #spinner2{#}
{#            height: 70px;#}
{#            width: 70px;#}
{#            border-left-color: darkturquoise;#}
{#            border-right-color: darkturquoise;#}
{#            animation: spin2 1.8s infinite linear;#}
{#        }#}
{#        @keyframes spin {#}
{#            from{#}
{#                transform: rotate(0deg);#}
{#            }#}
{#            to{#}
{#                transform: rotate(360deg);#}
{#            }#}
{#        }#}
{#        @keyframes spin2 {#}
{#            from{#}
{#                transform: rotate(0deg);#}
{#            }#}
{#            to{#}
{#                transform: rotate(-360deg);#}
{#            }#}
{#        }#}
{#    </style>#}
</head>
<body class="container-fluid" id="home">
{#    <div class="preload">#}
{#        <div class="spinner" id="spinner1">#}
{#            <div class="spinner" id="spinner2"></div>#}
{#        </div>#}
{#    </div>#}

    {% block content %}{% endblock content %}

    <div class="row text-center footer">
        <p>&copy; 2018. Kenyan Lifestyle. All rights reserved.</p>
    </div>
    <a href="#home" id="toTop" class="scroll" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
{#    <script>#}
{#        (function () {#}
{#            let preload = document.getElementById('preload');#}
{#            let loading = 0;#}
{#            let id = setInterval(frame, 64);#}
{#            #}
{#            function frame() {#}
{#                if (loading == 100) {#}
{#                    clearInterval(id);#}
{#                    window.open()#}
{#                }#}
{#            }#}
{#        })();#}
{#    </script>#}

    <script type="text/javascript" src="{% static 'web/js/jquery-2.1.4.min.js' %}"></script>
    <script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    {% block js %}{% endblock js %}

    <!-- cart js -->
    <script type="text/javascript" src="{% static 'web/js/minicart.js' %}"></script>
    <script type="text/javascript">
		shoe.render();
		shoe.cart.on('shoe_checkout', function (evt) {
			let items, len, i;

			if (this.subtotal() > 0) {
				items = this.items();

				for (i = 0, len = items.length; i < len; i++) {}
			}
		});
	</script>
    <!-- //cart js -->
    <!-- image zoom js -->
    <script type="text/javascript" src="{% static 'web/js/imagezoom.js' %}"></script>
    <!-- //image zoom js -->
    <!-- responsive tabs js -->
    <script type="text/javascript" src="{% static 'web/js/easy-responsive-tabs.js' %}"></script>
    <script type="text/javascript">
        $(document).ready(function () {
			$('#horizontalTab').easyResponsiveTabs({
				type: 'default', //Types: default, vertical, accordion
				width: 'auto', //auto or any width like 600px
				fit: true, // 100% fit in a container
				closed: 'accordion', // Start closed if in accordion view
				activate: function (event) { // Callback function if tab is switched
					let $tab = $(this);
					let $info = $('#tabInfo');
					let $name = $('span', $info);
					$name.text($tab.text());
					$info.show();
				}
			});
			$('#verticalTab').easyResponsiveTabs({
				type: 'vertical',
				width: 'auto',
				fit: true
			});
		});
    </script>
	<!-- FlexSlider -->
	<script type="text/javascript" src="{% static 'web/js/jquery.flexslider.js' %}"></script>
	<script type="text/javascript">
		// Can also be used with $(document).ready()
		$(window).load(function () {
			$('.flexslider').flexslider({
				animation: "slide",
				controlNav: "thumbnails"
			});
		});
	</script>
	<!-- //FlexSlider-->

	<!-- start-smoth-scrolling -->
    <script type="text/javascript" src="{% static 'web/js/move-top.js' %}"></script>
    <script type="text/javascript" src="{% static 'web/js/easing.js' %}"></script>
	<script type="text/javascript">
		jQuery(document).ready(function ($) {
			$(".scroll").click(function (event) {
				event.preventDefault();
				$('html,body').animate({
					scrollTop: $(this.hash).offset().top
				}, 1000);
			});
		});
	</script>
	<!-- //end-smoth-scrolling -->
</body>
</html>

templates/contacts.html
{% extends 'base_layout.html' %}
{% load static %}
{% block content %}
    <div class="mini-banner">
        {% include 'includes/navbar.html' %}
    </div>
    <div class="row" style="min-height: 100%!important;">
        <div class="col-md-4" style='background: url("{% static 'web/images/contactbg.jpg' %}") center cover;'>
            <h2>CONTACT US</h2>
            <h4>We'd love to hear from you...</h4>
            <address>
                MOBILE: <a href="tel:+254707081315">+254 707 081 315</a><br/>
                E-MAIL: <a href="mailto:johnlawi72@gmail.com">ijohnlawi72@gmail.com</a> <br/>
                WEBSITE: <a href="klifestyle.herokuapp.com">www.kenyanlifestyle.com</a>
            </address>
        </div>
        <div class="col-md-8">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d495.3524297676401!2d36.82382987152127!3d-1.2830740883278344!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x182f10d5ef82815f%3A0x2b087c5079b170a9!2sImenti+House!5e0!3m2!1sen!2ske!4v1530884646630"
                    width="800" height="600" frameborder="0" style="border:0" allowfullscreen></iframe>
        </div>
    </div>
{% endblock %}

templates/gallery.html
{% extends 'base_layout.html' %}
{% load static %}
{% block content %}
    <!-- banner -->
    {% include 'includes/navbar.html' %}

    <!-- Page Content -->
    <div class="container">
    <p>{{ message }}</p>

        <h4 class="my-4 text-center text-lg-left"><a href="{% url 'products:upload' %}">Upload your picture</a>
            wearing a Kenyan Lifestyle product for a chance to be featured in our gallery</h4>

        <div class="row text-center text-lg-left">

            {% for obj in object_list %}
            <div class="col-lg-3 col-md-4 col-xs-6">
                <a href="#" class="d-block mb-4 h-100">
                    <img class="img-fluid img-thumbnail" src="{{ obj.image.url }}" alt="{{ obj.name }}">
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/index.html
{% extends 'base_layout.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/shop.css' %}" />
    <!-- banner -->
    <div class="banner">
        {% include 'includes/navbar.html' %}
    </div>
    <!-- featured categories and pic -->
    <div class="row">
        <div class="featured">
            <h4 class="categories"><a href="#">BACKPACKS</a></h4>
            <h4 class="categories"><a href="#">PANTS</a></h4>
            <h4 class="categories"><a href="#">HOODIES</a></h4>
            <h4 class="categories"><a href="#">TOPS</a></h4>
        </div>
        <div class="featured">
            <div class="col-md-4 text-center">
                <div class="feat-container">
                    <h4>JACKETS</h4>
                    <div class="feat-img">
                        <img src="{% static 'images/IMG_8817.jpg' %}" alt="brown leather bag" class="img-responsive" />
                    </div>
                </div>
                <div class="feat-container">
                    <h4>PANTS</h4>
                    <div class="feat-img">
                        <img src="{% static 'images/IMG_8959.jpg' %}" alt="brown leather bag" class="img-responsive" />
                    </div>
                </div>
            </div>
            <div class="col-md-4 center">
                <img src="{% static 'images/kl.jpg' %}" alt="" class="img-responsive" />
            </div>
            <div class="col-md-4 text-center">
                <div class="feat-container">
                    <h4>TOPS</h4>
                    <div class="feat-img">
                        <img src="{% static 'images/IMG_8827.jpg' %}" alt="brown leather bag" class="img-responsive" />
                    </div>
                </div>
                <div class="feat-container">
                    <h4>BACK PACKS</h4>
                    <div class="feat-img">
                        <img src="{% static 'images/IMG_8843.jpg' %}" alt="brown leather bag" class="img-responsive" />
                    </div>
                </div>
            </div>
        </div>
    </div>
{#    <!-- best sellers -->#}
{#    <div>#}
{#        <div class="slider-frame">#}
{#            <div class="btn prev"></div>#}
{#            <div class="btn next"></div>#}
{#            <div class="slider-container">#}
{#                <div class="slide">0</div>#}
{#                <div class="slide">1</div>#}
{#                <div class="slide">2</div>#}
{#                <div class="slide">3</div>#}
{#                <div class="slide">4</div>#}
{#                <div class="slide">5</div>#}
{#                <div class="slide">6</div>#}
{#                <div class="slide">7</div>#}
{#                <div class="slide">8</div>#}
{#                <div class="slide">9</div>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
        <div class="row">
            <div class="left-ads-display col-md-12">
                <div class="wrapper_top_shop">
                    <div class="col-md-6 shop_left">
                        <img src="{% static 'images/banner3.jpg' %}" alt="">
                        <h6>40% off</h6>
                    </div>
                    <div class="col-md-6 shop_right">
                        <img src="{% static 'images/banner2.jpg' %}" alt="">
                        <h6>50% off</h6>
                    </div>
                    <div class="clearfix"></div>
                    <!-- product-sec1 -->
                    <div class="product-sec1">
                        <!--/mens-->
                        {% for obj in object_list %}
                        <div class="col-md-4 product-men">
                            <div class="product-shoe-info shoe">
                                <div class="men-pro-item">
                                    <div class="men-thumb-item">
                                        <img src="{{ obj.image.url }}" alt="{{ obj.name }}">
                                        <div class="men-cart-pro">
                                            <div class="inner-men-cart-pro">
                                                <a href="{{ obj.get_absolute_url }}" class="link-product-add-cart">Quick View</a>
                                            </div>
                                        </div>
                                        <span class="product-new-top">New</span>
                                    </div>
                                    <div class="item-info-product">
                                        <h4>
                                            <a href="{{ obj.get_absolute_url }}">{{ obj.name }}</a>
                                        </h4>
                                        <div class="info-product-price">
                                            <div class="grid_meta">
                                                <div class="product_price">
                                                    <div class="grid-price ">
                                                        <span class="money ">Kshs. {{ obj.price }}</span>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="shoe single-item hvr-outline-out">
                                                <form action="#" method="post">
                                                    <input type="hidden" name="cmd" value="_cart">
                                                    <input type="hidden" name="add" value="1">
                                                    <input type="hidden" name="shoe_item" value="{{ obj.name }}">
                                                    <input type="hidden" name="amount" value="obj.price">
                                                    <button type="submit" class="shoe-cart pshoe-cart"><i class="fa fa-cart-plus" aria-hidden="true"></i></button>

                                                    <a href="#" data-toggle="modal" data-target="#myModal1"></a>
                                                </form>

                                            </div>
                                        </div>
{#                                        <div class="clearfix"></div>#}
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                        <!-- //mens -->
                        <div class="clearfix"></div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    <!-- shop the look -->
    <div class="row text-center" id="look">
        <h3>SHOP THE LOOK </h3>
        <div class="col-xs-3 look-container">
            <img src="{% static 'images/IMG_8890.jpg' %}" alt="shop the look" class="img-responsive">
        </div>
        <div class="col-xs-3 look-container">
            <img src="{% static 'images/IMG_8922.jpg' %}" alt="shop the look" class="img-responsive">
        </div>
        <div class="col-xs-3 look-container">
            <img src="{% static 'images/IMG_8847.jpg' %}" alt="shop the look" class="img-responsive">
        </div>
        <div class="col-xs-3 look-container">
            <img src="{% static 'images/IMG_8971.jpg' %}" alt="shop the look" class="img-responsive">
        </div>
    </div>
{% endblock %}

templates/messages_display.html
{% if messages %}
        <div class="messages">
            <ul class="messages">
                {% for message in messages %}
                    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>
                        {{ message }}
                    </li>
                {% endfor %}
            </ul>
        </div>
{% endif %}

templates/product_form.html
{% extends 'base_layout.html' %}
{% block content %}
    <div class="mini-banner">
        {% include 'includes/navbar.html' %}
    </div>
    <form method="post" action="" enctype="multipart/form-data">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Add Product" />
    </form>
{% endblock %}

templates/shop.html
{% extends 'base_layout.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/shop.css' %}" />
    <!-- banner -->
    {% include 'includes/navbar.html' %}
    <!-- featured categories and pic -->

        <div class="row">
            <div class="left-ads-display col-md-12">
                <div class="wrapper_top_shop">
                    <!-- product-sec1 -->
                    <div class="product-sec1">
                        <!--/mens-->
                        {% for obj in object_list %}
                        <div class="col-md-4 product-men">
                            <div class="product-shoe-info shoe">
                                <div class="men-pro-item">
                                    <div class="men-thumb-item">
                                        <img src="{{ obj.image.url }}" alt="{{ obj.name }}">
                                        <div class="men-cart-pro">
                                            <div class="inner-men-cart-pro">
                                                <a href="{{ obj.get_absolute_url }}" class="link-product-add-cart">Quick View</a>
                                            </div>
                                        </div>
                                        <span class="product-new-top">New</span>
                                    </div>
                                    <div class="item-info-product">
                                        <h4>
                                            <a href="{{ obj.get_absolute_url }}">{{ obj.name }}</a>
                                        </h4>
                                        <div class="info-product-price">
                                            <div class="grid_meta">
                                                <div class="product_price">
                                                    <div class="grid-price ">
                                                        <span class="money ">Kshs. {{ obj.price }}</span>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="shoe single-item hvr-outline-out">
                                                <form action="#" method="post">
                                                    <input type="hidden" name="cmd" value="_cart">
                                                    <input type="hidden" name="add" value="1">
                                                    <input type="hidden" name="shoe_item" value="{{ obj.name }}">
                                                    <input type="hidden" name="amount" value="obj.price">
                                                    <button type="submit" class="shoe-cart pshoe-cart"><i class="fa fa-cart-plus" aria-hidden="true"></i></button>

                                                    <a href="#" data-toggle="modal" data-target="#myModal1"></a>
                                                </form>

                                            </div>
                                        </div>
{#                                        <div class="clearfix"></div>#}
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                        <!-- //mens -->
                        <div class="clearfix"></div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    <!-- shop the look -->
    <div class="row text-center" id="look">
        <h3>SHOP THE LOOK </h3>
        <div class="col-xs-3 look-container">
            <img src="{% static 'images/IMG_8890.jpg' %}" alt="shop the look" class="img-responsive">
        </div>
        <div class="col-xs-3 look-container">
            <img src="{% static 'images/IMG_8922.jpg' %}" alt="shop the look" class="img-responsive">
        </div>
        <div class="col-xs-3 look-container">
            <img src="{% static 'images/IMG_8847.jpg' %}" alt="shop the look" class="img-responsive">
        </div>
        <div class="col-xs-3 look-container">
            <img src="{% static 'images/IMG_8971.jpg' %}" alt="shop the look" class="img-responsive">
        </div>
    </div>
    <script src="{% static 'js/netflixCarousel.js' %}"></script>
{% endblock %}

templates/uploads.html
{% extends 'base_layout.html' %}{% load static %}
{% block content %}
    <style>
    .btn-primary{
        display: inline;
        margin-right: 20px;
    }
    </style>
    <div class="mini-banner">
        {% include 'includes/navbar.html' %}
    </div>
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <form class="form-horizontal" method="post" action="{% url 'products:upload' %}"
                  enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <div class="col-md-11 col-md-offset-1">
                        <label for="image" class="text-left">Choose an image</label>
                    </div>
                    <div class="col-md-11 col-md-offset-1">
                        <input type="file" id="image" />
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-2 col-md-offset-1">
                        <input type="submit" class="btn btn-primary" value="Add Image" />
                    </div>
                    <div class="col-sm-2 col-md-offset-1">
                        <a href="{% url 'products:gallery' %}" class="btn btn-primary">Go to Gallery</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="clearfix"></div>
    <!-- shop the look -->
    <div class="row text-center" id="look">
        <h3>SHOP THE LOOK </h3>
        <div class="col-xs-3 look-container">
            <img src="{% static 'images/IMG_8890.jpg' %}" alt="shop the look" class="img-responsive">
        </div>
        <div class="col-xs-3 look-container">
            <img src="{% static 'images/IMG_8922.jpg' %}" alt="shop the look" class="img-responsive">
        </div>
        <div class="col-xs-3 look-container">
            <img src="{% static 'images/IMG_8847.jpg' %}" alt="shop the look" class="img-responsive">
        </div>
        <div class="col-xs-3 look-container">
            <img src="{% static 'images/IMG_8971.jpg' %}" alt="shop the look" class="img-responsive">
        </div>
    </div>
{% endblock %}